/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompanyRouteImport } from './routes/company'
import { Route as CompanyIndexRouteImport } from './routes/company.index'
import { Route as CompanyIntelligenceRouteImport } from './routes/company.intelligence'
import { Route as CompanySkillsRouteImport } from './routes/company.skills'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyRoute = CompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyIndexRoute = CompanyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CompanyRoute,
} as any)
const CompanyIntelligenceRoute = CompanyIntelligenceRouteImport.update({
  id: '/intelligence',
  path: '/intelligence',
  getParentRoute: () => CompanyRoute,
} as any)
const CompanySkillsRoute = CompanySkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => CompanyRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/company': typeof CompanyRouteWithChildren
  '/company/intelligence': typeof CompanyIntelligenceRoute
  '/company/skills': typeof CompanySkillsRoute
  '/company/': typeof CompanyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/company/intelligence': typeof CompanyIntelligenceRoute
  '/company/skills': typeof CompanySkillsRoute
  '/company': typeof CompanyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/company': typeof CompanyRouteWithChildren
  '/company/intelligence': typeof CompanyIntelligenceRoute
  '/company/skills': typeof CompanySkillsRoute
  '/company/': typeof CompanyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/company' | '/company/intelligence' | '/company/skills' | '/company/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/company/intelligence' | '/company/skills' | '/company'
  id:
    | '__root__'
    | '/'
    | '/company'
    | '/company/intelligence'
    | '/company/skills'
    | '/company/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompanyRoute: typeof CompanyRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company': {
      id: '/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof CompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/': {
      id: '/company/'
      path: '/'
      fullPath: '/company/'
      preLoaderRoute: typeof CompanyIndexRouteImport
      parentRoute: typeof CompanyRoute
    }
    '/company/intelligence': {
      id: '/company/intelligence'
      path: '/intelligence'
      fullPath: '/company/intelligence'
      preLoaderRoute: typeof CompanyIntelligenceRouteImport
      parentRoute: typeof CompanyRoute
    }
    '/company/skills': {
      id: '/company/skills'
      path: '/skills'
      fullPath: '/company/skills'
      preLoaderRoute: typeof CompanySkillsRouteImport
      parentRoute: typeof CompanyRoute
    }
  }
}

interface CompanyRouteChildren {
  CompanyIntelligenceRoute: typeof CompanyIntelligenceRoute
  CompanySkillsRoute: typeof CompanySkillsRoute
  CompanyIndexRoute: typeof CompanyIndexRoute
}

const CompanyRouteChildren: CompanyRouteChildren = {
  CompanyIntelligenceRoute: CompanyIntelligenceRoute,
  CompanySkillsRoute: CompanySkillsRoute,
  CompanyIndexRoute: CompanyIndexRoute,
}

const CompanyRouteWithChildren =
  CompanyRoute._addFileChildren(CompanyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompanyRoute: CompanyRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
